### ISSUE TITLE
[Question]-CMakeLists.txt file to understand compile and Link in HIP environment

### ISSUE THREAD

**Issue by anilbommareddy** [ROCm/HIP-Examples#13]
Is any reference link or document to understand on "CMakeLists.txt" to compile and link in HCC Environment

Example1:
compile & link: hipcc
hipcc -c example.cpp.cpp -o main.o  [compile]
hipcc main.o -o Main [link]

Example 2:

compile(hipcc) and link(g++):
hipcc -c  example.cpp -o main.o   [compile]
g++ -L/opt/rocm/lib  -lhip_hcc main.o -o Main [link]

In above examples , compile and link done through command lines. it is need write in CMakeLists.txt

**Comment by ppanchad-amd** [comment]
@anilbommareddy Apologies for the lack of response. Do you still need assistance with this ticket? Thanks!

**Comment by anilbommareddy** [comment]
@ppanchad-amd  thank you for the response . No assistance required on  it .
