### ISSUE TITLE
GPU-STREAM git repo is out of date. 

### ISSUE THREAD

**Issue by damora** [ROCm/HIP-Examples#26]
GPU-STREAM code is using a deprecated version of hipLaunchKernel 
error: no matching function for call to 'hipLaunchKernel'
  hipLaunchKernel(HIP_KERNEL_NAME(triad_kernel), dim3(array_size/TBSIZE), dim3(TBSIZE), 0, 0, d_a, d_b, d_c);

**Comment by ppanchad-amd** [comment]
@damora Apologies for the lack of response. Closing this ticket since this repository is being replaced by [ROCm-examples](https://github.com/ROCm/rocm-examples). Thanks!
