### ISSUE TITLE
gpu-burn/common.h missing `<memory>` header 

### ISSUE THREAD

**Issue by colleeneb** [ROCm/HIP-Examples#28]
Hello,

It looks like std::unique_ptr is used without including the `<memory>` header. This code worked fine with AMD HIP, but I think it still technically needs the header included. (I found this when trying to compiler with HIPCL, which does need the `<memory>` header include.)

For example, adding something like:
https://github.com/colleeneb/HIP-Examples/blob/f00739a2dd6fe4dca41c1555105d4c332af236a5/gpu-burn/common.h#L9

I can submit a PR if you want, otherwise it's a one-line change so hopefully it's easy to do.

Thanks!

**Comment by ppanchad-amd** [comment]
@colleeneb Apologies for the lack of response. Internal ticket has been created to fix this issue. Thanks!

**Comment by jamesxu2** [comment]
Hi @colleeneb , thanks for the issue report. I think you are right, ```#include <memory>``` only exists in gpuburn.cpp but not the other source files in that repository and could cause issues. However, this repository is being replaced by [ROCm-examples](https://github.com/ROCm/rocm-examples) so we will not be updating it.
