### ISSUE TITLE
VectorAdd example doesn't work on build type release using Cmake

### ISSUE THREAD

**Issue by NicoDic98** [ROCm/HIP-Examples#32]
When trying out the Code from the VectorAdd example inside a Cmake project, 
the execution fails, when using the release flag as build type.
This is due to the NDEBUG flag being set.

This can be circumvented by not using the defined HIP_ASSERT directly, but by storing the return values and then putting those inside the HIP_ASSERT .
I'm not sure why this is exactly the case, because I would have expected that the code inside an ASSERT gets at least executed when NDEBUG is set.

**Comment by ppanchad-amd** [comment]
@NicoDic98 Apologies for the lack of response. Closing this ticket since this repository is being replaced by [ROCm-examples](https://github.com/ROCm/rocm-examples). Thanks!
