### ISSUE TITLE
Top level make option for linux distros

### ISSUE THREAD

**Issue by trixirt** [ROCm/HIP-Examples#40]
To be included in a linux distro, like fedora, it is expected that there be some top level controlling build infrastructure like cmake that builds against the distro's version of the hip and installs everything.

Can cmake infra, consistent with the other ROCm projects, be added to this project ?

**Comment by cjatin** [comment]
Will pass on the feedback to the team to see what they think of it.

**Comment by ppanchad-amd** [comment]
@trixirt Closing this ticket since this repository is being replaced by [ROCm-examples](https://github.com/ROCm/rocm-examples). Thanks!
